org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED -Dhttps.protocols=TLSv1.2,TLSv1.3 -Dkotlin.daemon.jvm.options=-Xmx768m -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.jvm.target.validation.mode=IGNORE
android.useAndroidX=true
android.enableJetifier=false
systemProp.https.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.kotlin.dsl.strictMode=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
kotlin.daemon.jvmargs=-Xmx768m
kotlin.code.style=official
kotlin.incremental=false
kotlin.jvm.target.validation.mode=IGNORE

# NDK 配置
# android.ndkVersion=r27d
# android.ndkPath=D:\\SDKTool\\android-ndk-r27d
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
