name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force overwrite existing release'
        required: false
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Java 环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: true

      # 获取依赖
      - name: Install dependencies
        run: flutter pub get

      # 运行代码格式检查
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      # 运行静态分析
      - name: Run analyzer
        run: flutter analyze

      # 运行测试
      - name: Run tests
        run: flutter test

      # 构建 Android Release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 上传构建产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 创建或覆盖 GitHub Release
      - name: Create or Overwrite Release
        if: github.event_name == 'workflow_dispatch' && inputs.force_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-release
          name: Latest Release
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/app-release.apk
          fail_on_unmatched_files: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}