name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Java 环境 (Flutter Android 构建需要)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'  # 使用最新稳定版本，可以根据需要调整
          channel: 'stable'
          cache: true

      # 获取依赖
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./xlist

      # 运行代码格式检查
      - name: Check code formatting
        run: dart format --set-exit-if-changed .
        working-directory: ./xlist

      # 运行静态分析
      - name: Run analyzer
        run: flutter analyze
        working-directory: ./xlist

      # 运行测试
      - name: Run tests
        run: flutter test
        working-directory: ./xlist

      # 构建 Android APK
      - name: Build APK
        run: flutter build apk --debug
        working-directory: ./xlist

      # 构建 iOS (仅在 macOS 运行器上)
      - name: Build iOS
        if: runner.os == 'macOS'
        run: flutter build ios --no-codesign
        working-directory: ./xlist

      # 上传构建产物（可选）
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: xlist/build/app/outputs/flutter-apk/app-debug.apk